# Generated by Django 5.2.7 on 2025-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_title_alter_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_datetime',
        ),
    ]
