# Generated by Django 5.2.7 on 2025-10-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_datetime']},
        ),
    ]
